import { Grid } from '@mui/material';
import { ReviewsRank } from '../../types/review';
import ReviewChartCard from './ReviewChartCard';

const DUMMY_REVIEWS_RANK: ReviewsRank[] = [
  {
    _id: '507f1f77bcf86cd799439011',
    title: 'DAMN. - 켄드릭 라마의 걸작에 대한 심층 분석',
    favoriteCount: 234,
    body: '켄드릭 라마의 DAMN.은 현대 힙합의 새로운 경지를 보여준다. 이 앨범은 종교적 상징성과 개인적 고뇌를 절묘하게 융합시킨 작품이다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b27355404f712deb84d0650a4b41',
    createdAt: '2024-11-10T10:30:00.000Z',
    user: {
      _id: 'user1',
      name: 'HipHop Critic',
      displayName: 'HipHopCritic',
      image: 'https://via.placeholder.com/150',
      email: 'critic@example.com',
      password: '',
      createdAt: '2024-01-15T09:00:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '4eLPsYPBmXABThSJ821sqY',
    albumTitle: 'DAMN.',
    albumRating: 4.8,
    artists: ['Kendrick Lamar'],
    artistGenre: ['Hip Hop', 'Conscious Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example1',
    length: 5,
  },
  {
    _id: '507f1f77bcf86cd799439012',
    title: 'To Pimp a Butterfly: 현대 힙합의 새로운 지평',
    favoriteCount: 187,
    body: 'To Pimp a Butterfly는 재즈와 힙합의 완벽한 융합을 보여준다. 켄드릭의 가장 야심찬 프로젝트로 평가받는 이 앨범은 음악적 실험과 사회적 메시지가 조화를 이룬다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273cdb645498cd3d8a2abcda13d',
    createdAt: '2024-11-08T14:20:00.000Z',
    user: {
      _id: 'user2',
      name: 'Jazz Enthusiast',
      displayName: 'JazzHop',
      image: 'https://via.placeholder.com/150',
      email: 'jazzhop@example.com',
      password: '',
      createdAt: '2024-02-20T11:30:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '7ycBtnsMtyVbbwTfJwRjSP',
    albumTitle: 'To Pimp a Butterfly',
    albumRating: 4.9,
    artists: ['Kendrick Lamar'],
    artistGenre: ['Hip Hop', 'Jazz Rap'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example2',
    length: 4,
  },
  {
    _id: '507f1f77bcf86cd799439013',
    title: 'Good Kid, M.A.A.D City - 스토리텔링의 완성',
    favoriteCount: 156,
    body: '켄드릭의 데뷔 정규앨범은 스토리텔링의 새로운 기준을 제시했다. 콤프턴에서의 성장 과정을 영화적 서사로 풀어낸 걸작이다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273d058e2460c04cd9b77daf705',
    createdAt: '2024-11-05T16:45:00.000Z',
    user: {
      _id: 'user3',
      name: 'Story Master',
      displayName: 'StoryTeller',
      image: 'https://via.placeholder.com/150',
      email: 'story@example.com',
      password: '',
      createdAt: '2024-03-10T14:15:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '3DGQ1iZ9XKUQxAUWjfC34w',
    albumTitle: 'good kid, m.A.A.d city',
    albumRating: 4.7,
    artists: ['Kendrick Lamar'],
    artistGenre: ['Hip Hop', 'West Coast Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example3',
    length: 6,
  },
  {
    _id: '507f1f77bcf86cd799439014',
    title: 'The Chronic - 닥터 드레의 전설적인 앨범',
    favoriteCount: 143,
    body: '웨스트코스트 힙합의 전설을 만든 불멸의 작품. G-Funk 사운드의 정점을 찍은 이 앨범은 힙합 역사에 길이 남을 명작이다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273c2c598fff6dc6c4d80bcb295',
    createdAt: '2024-11-03T12:15:00.000Z',
    user: {
      _id: 'user4',
      name: 'West Coast Legend',
      displayName: 'WestCoast',
      image: 'https://via.placeholder.com/150',
      email: 'westcoast@example.com',
      password: '',
      createdAt: '2024-04-05T16:20:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '6kBDZFXuLrZgHnvmPu9NsG',
    albumTitle: 'The Chronic',
    albumRating: 4.6,
    artists: ['Dr. Dre'],
    artistGenre: ['Hip Hop', 'G-Funk', 'West Coast Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example4',
    length: 3,
  },
  {
    _id: '507f1f77bcf86cd799439015',
    title: 'Illmatic - 나스의 불멸의 걸작',
    favoriteCount: 128,
    body: '이스트코스트 힙합의 최고봉을 보여주는 완벽한 앨범. 10개의 트랙 모두가 클래식인 이 앨범은 힙합의 교과서라 불린다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273f1cc7f5b0ad6f38c0ee5dd64',
    createdAt: '2024-11-01T09:30:00.000Z',
    user: {
      _id: 'user5',
      name: 'East Coast Soul',
      displayName: 'EastCoast',
      image: 'https://via.placeholder.com/150',
      email: 'eastcoast@example.com',
      password: '',
      createdAt: '2024-05-12T13:45:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '3kEtdS2pH6hKcMU9Wioob1',
    albumTitle: 'Illmatic',
    albumRating: 4.8,
    artists: ['Nas'],
    artistGenre: ['Hip Hop', 'East Coast Hip Hop', 'Hardcore Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example5',
    length: 4,
  },
  {
    _id: '507f1f77bcf86cd799439016',
    title: 'Enter the Wu-Tang - 무당클랜의 혁명',
    favoriteCount: 112,
    body: '힙합계에 혁명을 일으킨 Wu-Tang Clan의 데뷔작. 무술 영화 샘플과 독창적인 사운드로 힙합의 새로운 지평을 열었다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273c9b6ac52b598b90c7d8accd1',
    createdAt: '2024-10-29T18:20:00.000Z',
    user: {
      _id: 'user6',
      name: 'Wu Tang Master',
      displayName: 'WuTangFan',
      image: 'https://via.placeholder.com/150',
      email: 'wutang@example.com',
      password: '',
      createdAt: '2024-06-18T10:30:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '7HMmFQsKsljwTw8bS7lu19',
    albumTitle: 'Enter The Wu-Tang (36 Chambers)',
    albumRating: 4.5,
    artists: ['Wu-Tang Clan'],
    artistGenre: ['Hip Hop', 'East Coast Hip Hop', 'Hardcore Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example6',
    length: 5,
  },
  {
    _id: '507f1f77bcf86cd799439017',
    title: 'The Low End Theory - 트라이브의 완벽한 균형',
    favoriteCount: 98,
    body: 'A Tribe Called Quest의 걸작, 재즈와 힙합의 완벽한 조화. 얼터너티브 힙합의 교과서적인 작품으로 평가받는다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273c911160b6c65500b0d3db1cd',
    createdAt: '2024-10-27T11:45:00.000Z',
    user: {
      _id: 'user7',
      name: 'Alternative Vision',
      displayName: 'JazzRap',
      image: 'https://via.placeholder.com/150',
      email: 'jazzrap@example.com',
      password: '',
      createdAt: '2024-07-22T15:20:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '1oW3v5Har9mvXnGk0x4fHm',
    albumTitle: 'The Low End Theory',
    albumRating: 4.7,
    artists: ['A Tribe Called Quest'],
    artistGenre: ['Hip Hop', 'Jazz Rap', 'Alternative Hip Hop'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example7',
    length: 4,
  },
  {
    _id: '507f1f77bcf86cd799439018',
    title: 'Ready to Die - 비기의 데뷔작 분석',
    favoriteCount: 89,
    body: 'The Notorious B.I.G.의 데뷔작이 보여준 스토리텔링의 힘. 브루클린 스트리트의 현실을 날것 그대로 담아낸 걸작이다.',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b273f7e2c2a35edf4b2ac0e47828',
    createdAt: '2024-10-25T13:30:00.000Z',
    user: {
      _id: 'user8',
      name: 'Brooklyn Voice',
      displayName: 'BiggieFan',
      image: 'https://via.placeholder.com/150',
      email: 'biggie@example.com',
      password: '',
      createdAt: '2024-08-14T12:10:00.000Z',
      favorites: {},
      favoritesReview: {},
    },
    isFavorite: [],
    comments: [],
    albumId: '7w5GycQa7D1oVqOTvhtfPG',
    albumTitle: 'Ready to Die',
    albumRating: 4.6,
    artists: ['The Notorious B.I.G.'],
    artistGenre: ['Hip Hop', 'East Coast Hip Hop', 'Gangsta Rap'],
    previewUrl: 'https://p.scdn.co/mp3-preview/example8',
    length: 6,
  },
];

function ReviewChart() {
  return (
    <Grid container spacing={2}>
      {DUMMY_REVIEWS_RANK.slice(0, 8).map((review, index) => {
        return (
          <Grid key={review._id} size={{ xs: 12, sm: 6, md: 6 }}>
            <ReviewChartCard review={review} index={index} />
          </Grid>
        );
      })}
    </Grid>
  );
}

export default ReviewChart;
